CREATE TABLE IF NOT EXISTS metadata.table_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name VARCHAR(100) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    table_type VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT table_metadata_unique_table UNIQUE (schema_name, table_name)
);

CREATE TABLE IF NOT EXISTS metadata.column_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name VARCHAR(100) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    column_name VARCHAR(100) NOT NULL,
    data_type VARCHAR(100) NOT NULL,
    is_nullable BOOLEAN NOT NULL,
    is_primary_key BOOLEAN NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT column_metadata_unique_column UNIQUE (schema_name, table_name, column_name)
);

CREATE TABLE IF NOT EXISTS metadata.pipeline_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    source_tables TEXT[] NOT NULL,
    target_table VARCHAR(250) NOT NULL,
    load_type VARCHAR(50) NOT NULL,
    schedule VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS metadata.pipeline_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name VARCHAR(150) NOT NULL,
    status VARCHAR(50) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    rows_read BIGINT,
    rows_written BIGINT,
    error_message TEXT
);